name: cross_shop
description: "CrossShop - 跨端电商应用"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.0-34.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
